refactored metafunctions (`ansi`, `function.args`, `function.requires`, `log`)

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -1,56 +1,123 @@
 #!/usr/bin/env bash
 
-if [[ -n "${BASH}" ]] && [[ $- == *i* ]]; # [How return from .bashrc if not run interactively?](https://askubuntu.com/a/1070182)
-    then (( "${_VERBOSE}" >= 1 )) && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***"; # [Reliable way for a Bash script to get the full path to itself [duplicate]](https://stackoverflow.com/a/11114547)
-    else return;
-fi
+[[ -v BASH ]] || return 0; # [BASH](https://bash-hackers.docs.cern.ch/syntax/shellvars#bash) [Misc syntax](https://bash-hackers.docs.cern.ch/commands/classictest#misc_syntax)
 
-_source(){
-    [[ -f "$1" ]] && source "$1";
-    [[ -d "$1" ]] && find "$1/" -type f -not -name '.*' -print0 | xargs --max-args=1 source;
-}
+[[ $- == *i* ]] || return 0; # [How return from .bashrc if not run interactively?](https://askubuntu.com/a/1070182)
 
-_hostConfig(){
-    local hostName
-    hostName="$(hostname --long 2>/dev/null || echo "${HOSTNAME}")" # hostName=$(hostname; hostname --domain; hostname --all-fqdns; hostname --alias)
-    [[ "${HOSTSLOCAL[*]}" =~ ${hostName} ]] && _source "${XDG_CONFIG_HOME}/private/bash/local"
-    [[ "${HOSTSREMOTE[*]}" =~ ${hostName} ]] && _source "${XDG_CONFIG_HOME}/private/bash/remote"
-    [[ "${hostName}" =~ '.cern.ch'$ ]] && _source "${XDG_CONFIG_HOME}/bash/functions/cern"
-    [[ "${hostName}" =~ '.fnal.gov'$ ]] && _source "${XDG_CONFIG_HOME}/bash/functions/fnal"
-    [[ "${hostName}" =~ '.cms'$ ]] && _source "${XDG_CONFIG_HOME}/bash/functions/cms"
-}
+declare -A -g LOG=(['NOTSET']=0 ['DEBUG']=10 ['INFO']=20 ['WARNING']=30 ['ERROR']=40 ['CRITICAL']=50); # https://docs.python.org/3/howto/logging.html#logging-levels
+declare -A -g TXT; # [before BASH 4.2, associative array must be declared outside function in order to be global](https://stackoverflow.com/a/10806853/13019084)
 
-_textFormatting(){
+# Define an alias to pass "$FUNCNAME", positional parameters, and an ASCII "record separator" delimiter to `function.args` before passing the variable names.
+# Set a trap on `ERR` signal to force the parent function to break if `function.args` returns 64.
+alias args=$'trap "(( \$? == 64 )) && return 22" ERR; function.args "${FUNCNAME}" "$@" $\'\\030\'' # [https://bash-hackers.docs.cern.ch/commands/builtin/trap] [How to trap exit code in Bash script](https://stackoverflow.com/a/23637952/13019084) [Escaping characters in bash alias](https://stackoverflow.com/a/42954517)
+
+function ansi(){
     # [How can I print text in various colors?](https://mywiki.wooledge.org/BashFAQ/037)
-    # [Terminal codes (ANSI/VT100) introduction](https://wiki.bash-hackers.org/scripting/terminalcodes)
-    # [tput](https://linuxcommand.org/lc3_adv_tput.php#text-effects)
-    # [terminfo](https://invisible-island.net/xterm/terminfo-contents.html)
-    # [terminfo - terminal capability database](https://invisible-island.net/ncurses/man/terminfo.5.html#h3-Terminfo-Capabilities-Syntax)
+    # [Terminal codes (ANSI/VT100) introduction](https://bash-hackers.docs.cern.ch/scripting/terminalcodes)
+    # [Coloring Terminal Text: tput and ANSI Escape Sequences](https://www.codequoi.com/en/coloring-terminal-text-tput-and-ansi-escape-sequences/)
+    [[ -n "${NO_COLOR}" ]] && return 0;
+    local i;
     declare -a fg=('black' 'red' 'green' 'yellow' 'blue' 'magenta' 'cyan' 'white' 'BLACK' 'RED' 'GREEN' 'YELLOW' 'BLUE' 'MAGENTA' 'CYAN' 'WHITE');
-    declare -A attr=(['reset']='sgr0' ['bold']='bold' ['dim']='dim' ['italic']='sitm' ['underline']='smul' ['blink']='blink' ['invert']='rev' ['hide']='invis' ['strikethrough']='smxx' \
-                     ['clear']='sgr0' ['bright']='bold' ['faint']='dim' ['italics']='sitm' ['uline']='smul' ['flicker']='blink' ['reverse']='rev' ['invisible']='invis' ['strikeout']='smxx');
-    local key;
-    for ((key=0; key<=${#fg[@]}-1; key++)); do TXT["${fg[${key}]}"]="$(tput setaf ${key})"; done;
-    for ((key=0; key<=${#fg[@]}-1; key++)); do TXT["${fg[${key}]}BG"]="$(tput setab ${key})"; done;
-    for key in "${!attr[@]}"; do TXT[${key}]="$(tput ${attr[${key}]})"; done;
+    declare -A attr=(['reset']='sgr0' ['bold']='bold' ['dim']='dim' ['italic']='sitm' ['underline']='smul' ['blink']='blink' ['reverse']='rev' ['invisible']='invis' ['strikethrough']='smxx');
+                    # ['clear']='sgr0' ['bright']='bold' ['faint']='dim' ['italics']='sitm' ['uline']='smul' ['flicker']='blink' ['invert']='rev' ['hide']='invis' ['strikeout']='smxx');
+    for ((i=0; i<=${#fg[@]}-1; i++)); do
+        TXT["${fg[$i]}"]="$(tput setaf $i)";
+        TXT["${fg[$i]}BG"]="$(tput setab $i)";
+    done;
+    for i in "${!attr[@]}"; do
+        TXT["$i"]="$(tput "${attr[$i]}")";
+    done;
 }
 
-testColor(){
-    # [256-xterm-24bit-rgb-color-chart](http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html)
-    msgcat --color=test # [The environment variable TERM](https://www.gnu.org/software/gettext/manual/html_node/The-TERM-variable.html#The-TERM-variable)
-    for bg in {0..15}; do printf "$(tput setab $bg)%*s$(tput sgr0)" "$(tput cols)"; done
-    for fg in {0..15}; do for bg in {0..15}; do printf "$(tput setaf $fg)$(tput setab $bg)%s%02d %s%02d$(tput sgr0) " 'fg' "$fg" 'bg' "$bg"; done; echo; done
-    local colors=(black red green yellow blue magenta cyan white); for fg in "${colors[@]}"; do for bg in "${colors[@]}"; do printf "$(git config --get-color '' "${fg} ${bg}")%8s%8s$(git config --get-color '' 'reset') " "${fg}" "${bg}"; done; echo; done # [https://git-scm.com/docs/git-config#Documentation/git-config.txt-color]
+function assign.indirect(){
+    # [Assigning indirect/reference variables](https://mywiki.wooledge.org/BashFAQ/006#Assigning_indirect.2Freference_variables)
+    # [How to use a variable's value as another variable's name in bash](https://stackoverflow.com/a/9715739/13019084)
+    read -r -- "$1" <<< "$2"; # [https://bash-hackers.docs.cern.ch/commands/builtin/read]
+    log DEBUG "$(declare -p $1)"; # [https://bash-hackers.docs.cern.ch/commands/builtin/declare]
 }
 
-# [before BASH 4.2](https://wiki.bash-hackers.org/scripting/bashchanges#other_builtins_and_keywords), [associative array must be declared outside function in order to be global](https://stackoverflow.com/a/10806853/13019084)
-declare -A TXT # [https://wiki.bash-hackers.org/commands/builtin/declare] [https://wiki.bash-hackers.org/syntax/arrays]
-_textFormatting
+function function.args(){
+    # Convenience metafunction to define function arguments, including optional arguments with default values
+    # It expects "$FUNCNAME" (name of parent function), followed by the positional parameters passed to the parent function, folowed by an ASCII "record separator" delimiter, followed by the variable names for the parent function's required & optional arguments
+    # Variable names for optional arguments should be indicated by wrapping them in square brackets, e.g `[optional_argument]`
+    # A default value for optional arguments may be specified with an equal sign, e.g. `[optional_argument=default_value]`
+    # The passed positional parameters are assigned to the variable names as global variables (use `local` keyword in parent function to specify local variables)
+    # When calling the parent function, optional positional parameters may be ommited with a quoted empty string, ''
+    # If any required parameters are missing, the expected usage (with the expected positional parameters) is printed and an exit code of 64 is returned
+    local function_name param arg bracket_regex equals_regex opt_arg default_value; # [https://bash-hackers.docs.cern.ch/commands/builtin/local]
+    bracket_regex='[[]([[:print:]]+)[]]'; # matches one or more 'printable' character(s) enclosed in square brackets (and groups each match into an array named "$BASH_REMATCH") [https://bash-hackers.docs.cern.ch/syntax/shellvars#bash_rematch]
+    equals_regex='([[:print:]]+)[=]([[:print:]]+)'; # matches and groups one or more 'printable' character(s) followed by an '=' and matches and groups the following one or more 'printable' character(s).
 
-_source "${XDG_CONFIG_HOME}/bash/shellOptions"
-_source "${XDG_CONFIG_HOME}/bash/functions/meta"
-_source "${XDG_CONFIG_HOME}/bash/functions/functions"
-_source "${XDG_CONFIG_HOME}/private/bash/functions/functions"
-_source "${XDG_CONFIG_HOME}/bash/aliases/aliases"
-_source "${XDG_CONFIG_HOME}/bash/prompt/prompt"
-_hostConfig
+    function_name="$1"; # [https://bash-hackers.docs.cern.ch/syntax/shellvars#funcname]
+    shift; # [https://bash-hackers.docs.cern.ch/commands/builtin/shift]
+    IFS=$'\30' read -r param arg <<< "$*"; # [Octal 34 is the ASCII "file separator" character, and is unlikely to be present in your data](https://unix.stackexchange.com/a/628543) [https://en.wikipedia.org/wiki/Delimiter#ASCII_delimited_text] [https://bash-hackers.docs.cern.ch/scripting/posparams#mass_usage]
+    read -r -a param <<< "${param}"; # [https://bash-hackers.docs.cern.ch/commands/builtin/read]
+    read -r -a arg <<< "${arg}";
+
+    for (( i=0; i<${#arg[@]}; i++ )); do
+        if ! [[ "${arg[i]}" =~ ${bracket_regex} ]]; then # required arguments (not wrapped in square brackets)
+            [[ -z "${param[i]}" ]] && { printf "%s: ${TXT[red]}%s\n${TXT[reset]}" "usage" "${function_name} ${arg[*]}"; return 64; } # [https://bash-hackers.docs.cern.ch/syntax/arrays#getting_values]
+            [[ -n "${param[i]}" ]] && assign.indirect "${arg[i]}" "${param[i]}";
+        elif [[ "${arg[i]}" =~ ${bracket_regex} ]]; then # optional arguments (wrapped in square brackets)
+            opt_arg="${BASH_REMATCH[1]}"; # regex match group of characters enclosed in square brackets
+            ! [[ "${opt_arg}" =~ ${equals_regex} ]] && assign.indirect "${opt_arg}" "${param[i]}";
+            if [[ "${opt_arg}" =~ ${equals_regex} ]]; then
+                opt_arg="${BASH_REMATCH[1]}"; # regex match group of characters before '=' character
+                default_value="${BASH_REMATCH[2]}"; # regex match group of characters after '=' character
+                [[ -n "${param[i]}" ]] && assign.indirect "${opt_arg}" "${param[i]}";
+                [[ -z "${param[i]}" ]] && assign.indirect "${opt_arg}" "${default_value}";
+            fi
+        fi
+    done
+}
+
+function function.requires(){
+    # check whether argument is found in `$PATH` and whether it is executable.
+    local executable_path;
+    executable_path="$(command -v "$1")" && [[ -x "${executable_path}" ]] && return 0;
+    log ERROR "'$1' is required" && return 1;
+}
+
+function log(){
+    # [Simple logging levels in Bash](https://stackoverflow.com/a/48087251/13019084)
+    local log_priority="$1";
+    log.level "${log_priority}" || return 0;
+    local message="${log_priority}: $2";
+    (( "${LOG["${log_priority}"]}" >= "${LOG['INFO']}" )) && local date_time="$(date +'%Y-%m-%d %H:%M:%S.%3N')" || local date_time="${EPOCHREALTIME}";
+    local date_time_fmt="${TXT['dim']}${date_time}${TXT['reset']}";
+    local pad="$(( "${COLUMNS}" - "${#message}" + ${#date_time_fmt} - ${#date_time} ))"; # compensate for text formatting around `${date_time}`
+    message="$(log.message "${log_priority}" "${message}")";
+    printf "%s%${pad}s\n" "${message}" "${date_time_fmt}"; # [printf modifiers](https://bash-hackers.docs.cern.ch/commands/builtin/printf#modifiers)
+}
+
+function log.level(){
+    # verify that `log_priority` is valid key for `LOG` and check whether `log_priority` exceeds `LOG_LEVEL`.
+    local log_priority="$1";
+    [[ -z "${LOG[${log_priority}]}" ]] && log ERROR "'${log_priority}' is not a valid log level (must be one of: ${!LOG[*]})" && return 1;
+    (( ${LOG[${log_priority}]} >= ${LOG[${LOG_LEVEL}]} ))
+}
+
+function log.message(){
+    # apply text formatting around `message` based on the value of `log_priority`.
+    local log_priority="$1" message="$2";
+    case "${log_priority}" in
+        DEBUG) message="${TXT['BLACK']}${message}${TXT['reset']}";;
+        INFO) message="${TXT['green']}${message}${TXT['reset']}";;
+        WARNING) message="${TXT['yellow']}${message}${TXT['reset']}";;
+        ERROR) message="${TXT['red']}${message}${TXT['reset']}";;
+        CRITICAL) message="${TXT['blink']}${TXT['red']}${message}${TXT['reset']}";;
+        *) return 1;
+    esac
+    printf '%s\n' "${message}"
+}
+
+ansi;
+
+filepath.logger; # defines `log.debug.filepath` and `log.info.filepath` aliases (see `bash/profile`)
+
+log.info.filepath;
+
+source "${XDG_CONFIG_HOME}/bash/shopt";
+source.dir "${XDG_CONFIG_HOME}/bash/functions/"; # (see `bash/profile`)
+source.dir "${XDG_CONFIG_HOME}/bash/aliases/";
+source.dir "${XDG_CONFIG_HOME}/bash/prompt/";
